### PR TITLE
Add information on funding by MultiXscale to the support page

### PR DESCRIPTION
**Pull request by laraPPr**
Add information on funding by MultiXscale to the support page

### CODE REVIEW

**Comment by boegel** [comment]
@ocaisa OK like this?

**Comment by laraPPr** [comment]
Do we have do something about the deprecated emojis?

**Comment by boegel** [comment]
@laraPPr Yes, we should fix that first, ideally in a separate PR...

**Comment by laraPPr** [comment]
> @laraPPr Yes, we should fix that first, ideally in a separate PR...

https://github.com/EESSI/docs/pull/116

**Review by boegel — APPROVED** [review]

**Pull request merged**
