### PR TITLE
update overview of available software

### PR DESCRIPTION
**Pull request by EESSIbot**

### CODE REVIEW

**Review by ocaisa — APPROVED** [review]
Having gone through all these changes line by line, I approve

**Comment by boegel** [comment]
> Having gone through all these changes line by line, I approve

These PRs are going to be pretty much impossible to review, except perhaps noticing that this part of the docs is being totally destroyed... :)

**Comment by ocaisa** [comment]
Codespell is failing. I don't think we have much choice here but to tell it to ignore the directory with generated content

**Comment by boegel** [comment]
We will need to take some extra action here, because the spell checker is tripping over a typo that we've inherited from a `description` field in an easyconfig file:
```
Error: ./docs/available_software/data/json_data_detail.json:1: ofthe ==> of the
Error: ./docs/available_software/detail/PGPLOT.md:10: ofthe ==> of the
```

**Comment by boegel** [comment]
> Codespell is failing. I don't think we have much choice here but to tell it to ignore the directory with generated content

Yeah, makes sense: https://github.com/EESSI/docs/pull/193

**Comment by ocaisa** [comment]
Closing this and rerunning

**Pull request closed without merging**
